#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch_side.xyz"
EWW=$(which eww)
CFG="$HOME/.config/eww/leftbar_old/"

bash ~/.config/system_scripts/get_spotify_art

# windows not in use
# exit

## window list
w_ls="
    back \
    status \
    time \
    clse \
    day_dot \
    sys_usg \
    song \
    fetch \
    pfp
"
## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets
run_eww() {
	${EWW} --config "$CFG" open-many $w_ls
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close $w_ls
	rm "$FILE"
fi
