#!/bin/bash

## Open links in firefox
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=$(which eww)
cmd="firefox --new-tab"

close_dash() {
	${EWW} --config "$CFG" close \
		background profile system clock uptime music github \
		reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--mail" ]]; then
	close_dash && ${cmd} "https://mail.google.com"

elif [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com"

elif [[ "$1" == "--rd" ]]; then
	close_dash && ${cmd} "https://web.whatsapp.com"

elif [[ "$1" == "--tw" ]]; then
	close_dash && ${cmd} "https://leetcode.com/"

elif [[ "$1" == "--yt" ]]; then
	close_dash && ${cmd} "http://127.0.0.1:8080/youtube.com"

fi
